
spring:
  application:
    name: e-commerce
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: ecommerce
    password: ecommerce
    jpa:
      hibernate:
        dialect:
          PostgreSQLDialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 80
  email: andrew.mello@diverproject.org

hibernate:
  show_sql: true
  generate_ddl: true
  dialect: org.hibernate.dialect.MySQL8Dialect
